# DO NOT EDIT THIS FILE!!!!!!!!!!!!!!!!!!!!!!!!!
import PySimpleGUI as sg
import json
import os

FLASHCARD_FILE = 'flashcards.json'

# Load flashcards from file
def load_flashcards():
    if os.path.exists(FLASHCARD_FILE):
        with open(FLASHCARD_FILE, 'r') as f:
            data = json.load(f)
            # Convert old formats if needed
            if isinstance(data, list):
                new_data = []
                for item in data:
                    if isinstance(item, str):
                        new_data.append({'name': f'Card {len(new_data)+1}', 'terms': [item]})
                    elif isinstance(item, dict):
                        if 'content' in item:
                            item['terms'] = [item.pop('content')]
                        if 'terms' not in item:
                            item['terms'] = []
                        new_data.append(item)
                return new_data
            return data
    return []

# Save flashcards to file
def save_flashcards(flashcards):
    with open(FLASHCARD_FILE, 'w') as f:
        json.dump(flashcards, f, indent=4)

flashcards = load_flashcards()

def get_flashcard_names():
    return [fc['name'] for fc in flashcards]

def get_flashcard_by_name(name):
    for fc in flashcards:
        if fc['name'] == name:
            return fc
    return None

sg.theme('GreenTan')

layout = [
    [sg.Text('Flashcard Name:'), sg.Input(key='-NAME-', size=(25, 1))],
    [sg.Button('Create / Select Flashcard')],
    [sg.Text('Add Term:'), sg.Input(key='-TERM-', size=(25, 1)), sg.Button('Add Term')],
    [sg.Button('Delete Selected Term')],
    [sg.Listbox(values=[], size=(40, 8), key='-TERMS-', enable_events=True)],
    [sg.Button('Save Flashcard')],
    [sg.Text('All Flashcards:')],
    [sg.Listbox(values=get_flashcard_names(), size=(30, 8), key='-CARDLIST-', enable_events=True)],
]

window = sg.Window('Flashcard Editor', layout, font=('Helvetica', 12), finalize=True)

selected_card = None

def update_flashcard_list():
    window['-CARDLIST-'].update(values=get_flashcard_names())

def update_term_list(card):
    window['-TERMS-'].update(values=card['terms'])

while True:
    event, values = window.read()
    if event == sg.WINDOW_CLOSED:
        save_flashcards(flashcards)
        break

    if event == 'Create / Select Flashcard':
        name = values['-NAME-'].strip()
        if not name:
            sg.popup_error("Please enter a flashcard name.")
            continue

        card = get_flashcard_by_name(name)
        if not card:
            card = {'name': name, 'terms': []}
            flashcards.append(card)
            update_flashcard_list()

        selected_card = card
        update_term_list(selected_card)

    elif event == 'Add Term' and selected_card:
        term = values['-TERM-'].strip()
        if term:
            selected_card['terms'].append(term)
            update_term_list(selected_card)
            window['-TERM-'].update('')

    elif event == 'Delete Selected Term' and selected_card:
        selected_terms = values['-TERMS-']
        if selected_terms:
            for term in selected_terms:
                if term in selected_card['terms']:
                    selected_card['terms'].remove(term)
            update_term_list(selected_card)

    elif event == 'Save Flashcard':
        save_flashcards(flashcards)
        sg.popup('Flashcard saved!')

    elif event == '-CARDLIST-':
        name = values['-CARDLIST-'][0]
        card = get_flashcard_by_name(name)
        if card:
            selected_card = card
            window['-NAME-'].update(name)
            update_term_list(selected_card)

window.close()